### ISSUE TITLE
Exception in module

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-retention-mongodb#3]
When restarting scheduler : 
```
2014-03-14 08:58:09,462 [1394783889] Error : The instance MongodbRetention raise an exception [Errno 4] Interrupted system call. I disable it and set it to restart it later
2014-03-14 08:58:09,463 [1394783889] Error : Exception trace follows: Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/shinken/scheduler.py", line 368, in hook_point
 f(self)
 File "/var/lib/shinken/modules/retention-mongodb/module.py", line 138, in hook_save_retention
 self.services_fs.delete(key)
 File "/usr/lib/python2.7/dist-packages/gridfs/__init__.py", line 232, in delete
 self.__files.remove({"_id": file_id}, safe=True)
 File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 481, in remove
 safe, kwargs, self.__uuid_subtype), safe)
 File "/usr/lib/python2.7/dist-packages/pymongo/connection.py", line 748, in _send_message
 raise AutoReconnect(str(e))
AutoReconnect: [Errno 4] Interrupted system call
```

**Comment by olivierHa** [comment]
Hello @mohierf ,
Do you still have this "old" issue ?
Want me to investigate ?

**Comment by mohierf** [comment]
nope
